name: Setup Node and Dependencies
description: Common setup for Node.js with platform-specific dependencies

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: '22'
  skip-native-deps:
    description: Skip native dependency installation
    required: false
    default: 'false'
  install-xvfb:
    description: Install xvfb for headless display (Linux only)
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install Linux dependencies
      if: runner.os == 'Linux' && inputs.skip-native-deps != 'true'
      shell: bash
      run: |
        sudo apt-get update
        deps="libusb-1.0-0-dev libudev-dev"
        if [ "${{ inputs.install-xvfb }}" = "true" ]; then
          deps="$deps xvfb"
        fi
        sudo apt-get install -y $deps

    - name: Install macOS dependencies
      if: runner.os == 'macOS' && inputs.skip-native-deps != 'true'
      shell: bash
      run: brew install libusb python-setuptools

    - name: Install npm dependencies
      shell: bash
      run: |
        if [ "${{ inputs.skip-native-deps }}" = "true" ]; then
          npm ci --ignore-scripts
        else
          npm ci
        fi
