/**
 * Application error codes.
 */
export enum ErrorCode {
  // General
  UNKNOWN = 'UNKNOWN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',

  // Device errors
  DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',
  DEVICE_ACCESS_DENIED = 'DEVICE_ACCESS_DENIED',
  DEVICE_BUSY = 'DEVICE_BUSY',
  DEVICE_DISCONNECTED = 'DEVICE_DISCONNECTED',

  // Stream errors
  STREAM_ERROR = 'STREAM_ERROR',
  STREAM_ACQUISITION_FAILED = 'STREAM_ACQUISITION_FAILED',
  STREAM_TIMEOUT = 'STREAM_TIMEOUT',

  // Capture errors
  CAPTURE_FAILED = 'CAPTURE_FAILED',
  RECORDING_FAILED = 'RECORDING_FAILED',

  // Transcode errors
  TRANSCODE_FAILED = 'TRANSCODE_FAILED',
  TRANSCODE_CANCELLED = 'TRANSCODE_CANCELLED',

  // GPU errors
  GPU_NOT_SUPPORTED = 'GPU_NOT_SUPPORTED',
  GPU_CONTEXT_LOST = 'GPU_CONTEXT_LOST',
  SHADER_COMPILATION_FAILED = 'SHADER_COMPILATION_FAILED',

  // IPC errors
  IPC_ERROR = 'IPC_ERROR',
  IPC_TIMEOUT = 'IPC_TIMEOUT'
}
