// Generated by PrismGB tooling.
// Source: src/shared/ipc/ipc.manifest.json

import type {
  DeviceInfoPayload,
  DeviceStatusPayload,
  GpuPolicyPayload,
  LoginItemGetResponse,
  LoginItemSetResponse,
  ProcessMetricsResponse,
  ShellOpenExternalResponse,
  TranscodeCancelResponse,
  TranscodeCancelledPayload,
  TranscodeCompletedPayload,
  TranscodeErrorPayload,
  TranscodeFormat,
  TranscodeProgressPayload,
  TranscodeStartOptions,
  TranscodeStartResponse,
  TranscodeStatusResponse,
  UpdateCheckResponse,
  UpdateDownloadResponse,
  UpdateErrorPayload,
  UpdateGetStatusResponse,
  UpdateInfoPayload,
  UpdateInstallResponse,
  UpdateProgressPayload,
  WindowIsFullscreenResponse,
  WindowSetFullscreenResponse
} from '@prismgb/ipc';

export {};

type Unsubscribe = () => void;

interface DeviceAPI {
  getDeviceStatus(): Promise<DeviceStatusPayload>;
  onDeviceConnected(callback: (payload: DeviceInfoPayload) => void): Unsubscribe;
  onDeviceDisconnected(callback: (payload: DeviceInfoPayload | null | undefined) => void): Unsubscribe;
}

interface ShellAPI {
  openExternal(url: string): Promise<ShellOpenExternalResponse>;
}

interface WindowAPI {
  onEnterFullscreen(callback: () => void): Unsubscribe;
  onLeaveFullscreen(callback: () => void): Unsubscribe;
  onResized(callback: () => void): Unsubscribe;
  setFullScreen(enabled: boolean): Promise<WindowSetFullscreenResponse>;
  isFullScreen(): Promise<WindowIsFullscreenResponse>;
}

interface UpdateAPI {
  getStatus(): Promise<UpdateGetStatusResponse>;
  checkForUpdates(): Promise<UpdateCheckResponse>;
  downloadUpdate(): Promise<UpdateDownloadResponse>;
  installUpdate(): Promise<UpdateInstallResponse>;
  onAvailable(callback: (payload: UpdateInfoPayload) => void): Unsubscribe;
  onNotAvailable(callback: (payload: UpdateInfoPayload) => void): Unsubscribe;
  onProgress(callback: (payload: UpdateProgressPayload) => void): Unsubscribe;
  onDownloaded(callback: (payload: UpdateInfoPayload) => void): Unsubscribe;
  onError(callback: (payload: UpdateErrorPayload) => void): Unsubscribe;
}

interface MetricsAPI {
  getProcessMetrics(): Promise<ProcessMetricsResponse>;
}

interface GpuAPI {
  getPolicy(): Promise<GpuPolicyPayload>;
}

interface LoginItemAPI {
  get(): Promise<LoginItemGetResponse>;
  set(enabled: boolean): Promise<LoginItemSetResponse>;
}

interface TranscodeAPI {
  start(inputBuffer: ArrayBuffer, format: TranscodeFormat, outputFilename?: string, options?: TranscodeStartOptions): Promise<TranscodeStartResponse>;
  cancel(jobId: string): Promise<TranscodeCancelResponse>;
  getStatus(): Promise<TranscodeStatusResponse>;
  onProgress(callback: (payload: TranscodeProgressPayload) => void): Unsubscribe;
  onCompleted(callback: (payload: TranscodeCompletedPayload) => void): Unsubscribe;
  onError(callback: (payload: TranscodeErrorPayload) => void): Unsubscribe;
  onCancelled(callback: (payload: TranscodeCancelledPayload) => void): Unsubscribe;
}

declare global {
  interface Window {
    deviceAPI?: DeviceAPI;
    shellAPI?: ShellAPI;
    windowAPI?: WindowAPI;
    updateAPI?: UpdateAPI;
    metricsAPI?: MetricsAPI;
    gpuAPI?: GpuAPI;
    loginItemAPI?: LoginItemAPI;
    transcodeAPI?: TranscodeAPI;
  }

  var deviceAPI: DeviceAPI | undefined;
  var shellAPI: ShellAPI | undefined;
  var windowAPI: WindowAPI | undefined;
  var updateAPI: UpdateAPI | undefined;
  var metricsAPI: MetricsAPI | undefined;
  var gpuAPI: GpuAPI | undefined;
  var loginItemAPI: LoginItemAPI | undefined;
  var transcodeAPI: TranscodeAPI | undefined;
}
