import type { AppOrchestrator } from '@renderer/application/orchestrators/app.orchestrator';
import type { CaptureOrchestrator } from '@renderer/application/orchestrators/capture.orchestrator';
import type { DeviceOrchestrator } from '@renderer/application/orchestrators/device.orchestrator';
import type { PerformanceOrchestrator } from '@renderer/application/orchestrators/performance.orchestrator';
import type { SettingsOrchestrator } from '@renderer/application/orchestrators/settings.orchestrator';
import type { StreamingAudioOrchestrator } from '@renderer/application/orchestrators/streaming-audio.orchestrator';
import type { StreamingOrchestrator } from '@renderer/application/orchestrators/streaming.orchestrator';
import type { UISetupOrchestrator } from '@renderer/application/orchestrators/ui-setup.orchestrator';
import type { AppState } from '@renderer/application/state/app-state';
import type { DeviceChangeDebounceAdapter } from '@renderer/infrastructure/adapters/devices/device-change-debounce.adapter';
import type { DeviceIpcAdapter } from '@renderer/infrastructure/adapters/devices/device-ipc.adapter';
import type { ReducedMotionAdapter } from '@renderer/infrastructure/adapters/reduced-motion.adapter';
import type { UserActivityAdapter } from '@renderer/infrastructure/adapters/user-activity.adapter';
import type { ProcessMetricsResponse, DeviceStatusPayload } from '@prismgb/ipc';
import type { BrowserMediaAdapter } from '@renderer/infrastructure/browser/browser-media.adapter.js';
import type { BrowserStorageAdapter } from '@renderer/infrastructure/browser/browser-storage.adapter.js';
import type { EventBus } from '@renderer/infrastructure/events/event-bus.class.js';
import type { StreamingAdapterFactory } from '@renderer/infrastructure/factories/streaming-adapter.factory';
import type { StreamingRendererFactory } from '@renderer/infrastructure/factories/streaming-renderer.factory';
import type { RendererLogger } from '@renderer/infrastructure/logging/logger.factory.js';
import type { CaptureSaveService } from '@renderer/infrastructure/services/capture/capture-save.service';
import type { CaptureService } from '@renderer/infrastructure/services/capture/capture.service';
import type { CaptureGpuRecordingService } from '@renderer/infrastructure/services/capture/gpu-recording.service';
import type { DeviceMediaService } from '@renderer/infrastructure/services/devices/device-media.service';
import type { DeviceOperationSequencerService } from '@renderer/infrastructure/services/devices/device-operation-sequencer.service';
import type { PerformanceAnimationService } from '@renderer/infrastructure/services/performance/performance-animation.service';
import type { PerformanceMetricsService } from '@renderer/infrastructure/services/performance/performance-metrics.service';
import type { PerformanceStateService } from '@renderer/infrastructure/services/performance/performance-state.service';
import type { NotesService } from '@renderer/infrastructure/services/notes/notes.service';
import type { SettingsFullscreenService } from '@renderer/infrastructure/services/settings/fullscreen.service';
import type { PresentationModeService } from '@renderer/infrastructure/services/settings/presentation-mode.service';
import type { SettingsService } from '@renderer/infrastructure/services/settings/settings.service';
import type { StreamingAudioPipelineService } from '@renderer/infrastructure/services/streaming/audio-pipeline.service';
import type { StreamingCanvasService } from '@renderer/infrastructure/services/streaming/streaming-canvas.service';
import type { StreamingCanvasRenderer } from '@renderer/infrastructure/services/streaming/canvas-renderer';
import type { GpuFrameBuffer } from '@renderer/infrastructure/services/streaming/gpu-frame-buffer';
import type { StreamingGpuRendererService } from '@renderer/infrastructure/services/streaming/gpu-renderer.service';
import type { GpuWorkerManager } from '@renderer/infrastructure/services/streaming/gpu-worker-manager';
import type { StreamingHealthService } from '@renderer/infrastructure/services/streaming/health.service';
import type { StreamingRenderPipelineService } from '@renderer/infrastructure/services/streaming/render-pipeline.service';
import type { StreamingService } from '@renderer/infrastructure/services/streaming/streaming.service';
import type { TranscodeService } from '@renderer/infrastructure/services/transcode/transcode.service';
import type { UpdateService } from '@renderer/infrastructure/services/updates/update.service';
import type { CaptureUIBridge } from '@renderer/presentation/bridges/capture-ui.bridge';
import type { TranscodeUIBridge } from '@renderer/presentation/bridges/transcode-ui.bridge';
import type { UIEventBridge } from '@renderer/presentation/bridges/ui-event.bridge';
import type { UpdateUIBridge } from '@renderer/presentation/bridges/update-ui.bridge';
import type { UIComponentRegistry } from '@renderer/presentation/controller/component.registry.js';
import type { UIController } from '@renderer/presentation/controller/ui.controller.js';
import type { BodyClassManager } from '@renderer/presentation/effects/body-class.class';
import type { UIEffects } from '@renderer/presentation/effects/ui-effects.class';
import type { AnimationCache } from '@renderer/infrastructure/utils/performance-cache.utils';

export interface RendererContainerMap {
  eventBus: EventBus;
  loggerFactory: RendererLogger;
  storageService: BrowserStorageAdapter;
  browserMediaService: BrowserMediaAdapter;
  visibilityAdapter: {
    isHidden: () => boolean;
    onVisibilityChange: (callback: (hidden: boolean) => void) => () => void;
  };
  userActivityAdapter: UserActivityAdapter;
  reducedMotionAdapter: ReducedMotionAdapter;
  metricsAdapter: {
    isAvailable: () => boolean;
    getProcessMetrics: () => Promise<ProcessMetricsResponse>;
  };
  deviceIpcAdapter: DeviceIpcAdapter;
  deviceChangeDebounceAdapter: DeviceChangeDebounceAdapter;
  animationCache: AnimationCache;
  canvasRenderer: StreamingCanvasRenderer;
  streamingCanvasService: StreamingCanvasService;
  streamHealthService: StreamingHealthService;
  gpuFrameBuffer: GpuFrameBuffer;
  gpuWorkerManager: GpuWorkerManager;
  gpuRendererService: StreamingGpuRendererService;
  streamingRendererFactory: StreamingRendererFactory;
  renderPipelineService: StreamingRenderPipelineService;
  ipcClient: unknown;
  deviceStatusProvider: {
    getDeviceStatus: () => Promise<DeviceStatusPayload>;
  };
  adapterFactory: StreamingAdapterFactory;
  deviceMediaService: DeviceMediaService;
  deviceOperationSequencer: DeviceOperationSequencerService;
  streamingService: StreamingService;
  captureService: CaptureService;
  gpuRecordingService: CaptureGpuRecordingService;
  transcodeService: TranscodeService;
  captureSaveService: CaptureSaveService;
  settingsService: SettingsService;
  notesService: NotesService;
  updateService: UpdateService;
  streamingAudioPipelineService: StreamingAudioPipelineService;
  appState: AppState;
  uiComponentRegistry: UIComponentRegistry;
  uiEffects: UIEffects;
  bodyClassManager: BodyClassManager;
  uiEventBridge: UIEventBridge;
  presentationModeService: PresentationModeService;
  captureUiBridge: CaptureUIBridge;
  transcodeUiBridge: TranscodeUIBridge;
  updateUiBridge: UpdateUIBridge;
  deviceOrchestrator: DeviceOrchestrator;
  streamingAudioOrchestrator: StreamingAudioOrchestrator;
  streamingOrchestrator: StreamingOrchestrator;
  captureOrchestrator: CaptureOrchestrator;
  settingsOrchestrator: SettingsOrchestrator;
  fullscreenService: SettingsFullscreenService;
  performanceOrchestrator: PerformanceOrchestrator;
  performanceMetricsService: PerformanceMetricsService;
  performanceStateService: PerformanceStateService;
  animationPerformanceService: PerformanceAnimationService;
  uiSetupOrchestrator: UISetupOrchestrator;
  appOrchestrator: AppOrchestrator;
  uiController: UIController;
}
