// AUTOGENERATED DEPENDENCY INJECTION CONTAINER - DO NOT EDIT DIRECTLY

import { EventBus } from './infrastructure/events/event-bus.class';
import { RendererLogger } from './infrastructure/logging/logger.factory';
import { DeviceConnectionService } from './infrastructure/services/devices/device-connection.service';
import { DeviceStorageService } from './infrastructure/services/devices/device-storage.service';
import { DeviceMediaService } from './infrastructure/services/devices/device-media.service';
import { DeviceService } from './infrastructure/services/devices/device.service';
import { DeviceOperationSequencerService } from './infrastructure/services/devices/device-operation-sequencer.service';
import { DeviceOrchestrator } from './application/orchestrators/device.orchestrator';
import { StreamingService } from './infrastructure/services/streaming/streaming.service';
import { AppState } from './application/state/app-state';
import { StreamingViewService } from './infrastructure/services/streaming/streaming-view.service';
import { StreamingRenderPipelineService } from './infrastructure/services/streaming/render-pipeline.service';
import { CaptureGpuRecordingService } from './infrastructure/services/capture/gpu-recording.service';
import { SettingsService } from './infrastructure/services/settings/settings.service';
import { StreamingOrchestrator } from './application/orchestrators/streaming.orchestrator';
import { StreamingAudioPipelineService } from './infrastructure/services/streaming/audio-pipeline.service';
import { StreamingAudioOrchestrator } from './application/orchestrators/streaming-audio.orchestrator';
import { CaptureService } from './infrastructure/services/capture/capture.service';
import { StreamingGpuRendererService } from './infrastructure/services/streaming/gpu-renderer.service';
import { TranscodeService } from './infrastructure/services/transcode/transcode.service';
import { CaptureSaveService } from './infrastructure/services/capture/capture-save.service';
import { CaptureOrchestrator } from './application/orchestrators/capture.orchestrator';
import { SettingsPreferencesOrchestrator } from './application/orchestrators/preferences.orchestrator';
import { SettingsFullscreenService } from './infrastructure/services/settings/fullscreen.service';
import { SettingsCinematicModeService } from './infrastructure/services/settings/cinematic-mode.service';
import { SettingsDisplayModeOrchestrator } from './application/orchestrators/display-mode.orchestrator';
import { UpdateService } from './infrastructure/services/updates/update.service';
import { UpdateUiService } from './infrastructure/services/updates/update-ui.service';
import { UpdateOrchestrator } from './application/orchestrators/update.orchestrator';
import { NotesService } from './infrastructure/services/notes/notes.service';
import { UISetupOrchestrator } from './application/orchestrators/ui-setup.orchestrator';
import { PerformanceAnimationService } from './infrastructure/services/performance/performance-animation.service';
import { BodyClassManager } from './presentation/effects/body-class.class';
import { PerformanceAnimationOrchestrator } from './application/orchestrators/performance-animation.orchestrator';
import { MetricsAdapter } from './infrastructure/adapters/platform/metrics.adapter';
import { PerformanceMetricsService } from './infrastructure/services/performance/performance-metrics.service';
import { PerformanceMetricsOrchestrator } from './application/orchestrators/performance-metrics.orchestrator';
import { VisibilityAdapter } from './infrastructure/adapters/visibility.adapter';
import { UserActivityAdapter } from './infrastructure/adapters/user-activity.adapter';
import { ReducedMotionAdapter } from './infrastructure/adapters/reduced-motion.adapter';
import { PerformanceStateService } from './infrastructure/services/performance/performance-state.service';
import { PerformanceStateOrchestrator } from './application/orchestrators/performance-state.orchestrator';
import { AppOrchestrator } from './application/orchestrators/app.orchestrator';
import { BrowserMediaAdapter } from './infrastructure/browser/browser-media.adapter';
import { PresentationModeService } from './infrastructure/services/settings/presentation-mode.service';
import { StreamingCanvasLifecycleService } from './infrastructure/services/streaming/canvas-lifecycle.service';
import { StreamingGpuRenderLoopService } from './infrastructure/services/streaming/gpu-render-loop.service';
import { GpuWorkerManager } from './infrastructure/services/streaming/gpu-worker-manager';
import { StreamingHealthService } from './infrastructure/services/streaming/health.service';
import { StreamingViewportService } from './infrastructure/services/streaming/viewport.service';
import { CaptureUIBridge } from './presentation/bridges/capture-ui.bridge';
import { TranscodeUIBridge } from './presentation/bridges/transcode-ui.bridge';
import { UIEventBridge } from './presentation/bridges/ui-event.bridge';
import { UIEffects } from './presentation/effects/ui-effects.class';

import { BrowserStorageAdapter } from './infrastructure/browser/browser-storage.adapter';
import { PROTECTED_STORAGE_KEYS } from '../shared/config/storage-keys.config';
import { DeviceIpcAdapter } from './infrastructure/adapters/devices/device-ipc.adapter';
import { DeviceChangeDebounceAdapter } from './infrastructure/adapters/devices/device-change-debounce.adapter';
import { StreamingCanvasRenderLoopService } from './infrastructure/services/streaming/canvas-render-loop.service';
import { GpuFrameBuffer } from './infrastructure/services/streaming/gpu-frame-buffer';
import { StreamingRendererFactory } from './infrastructure/factories/streaming-renderer.factory';
import { StreamingGpuRendererAdapter } from './infrastructure/adapters/streaming/gpu-renderer.adapter';
import { StreamingCanvas2DRendererAdapter } from './infrastructure/adapters/streaming/canvas2d-renderer.adapter';
import { DeviceIpcStatusAdapter } from './infrastructure/adapters/devices/device-ipc-status.adapter';
import { StreamingAdapterFactory } from './infrastructure/factories/streaming-adapter.factory';
import { DeviceChromaticAdapter } from './infrastructure/adapters/devices/chromatic/chromatic.adapter';
import { chromaticConfig } from '../shared/features/devices/profiles/chromatic/device-chromatic.config';
import { UIComponentRegistry } from './presentation/controller/component.registry';
import { rendererUiComponentDefinitions } from './presentation/controller/ui-component.catalog';
import { AnimationCache } from '../shared/utils/performance-cache.utils';

export class GeneratedContainer {
  public cache: Map<string, { value: unknown }> = new Map();
  public registrations: Record<string, any> = {};
  private instances: Map<string, any> = new Map();

  constructor(overrides: Record<string, any> = {}) {
    // Pre-seed all static tokens
    const staticTokens = [
  "storageService",
  "deviceIpcAdapter",
  "deviceChangeDebounceAdapter",
  "canvasRenderLoopService",
  "gpuFrameBuffer",
  "streamingRendererFactory",
  "ipcClient",
  "deviceStatusProvider",
  "adapterFactory",
  "uiComponentRegistry",
  "animationCache",
  "eventBus",
  "loggerFactory",
  "deviceConnectionService",
  "deviceStorageService",
  "deviceMediaService",
  "deviceService",
  "deviceOperationSequencer",
  "deviceOrchestrator",
  "streamingService",
  "appState",
  "streamViewService",
  "renderPipelineService",
  "gpuRecordingService",
  "settingsService",
  "streamingOrchestrator",
  "streamingAudioPipelineService",
  "streamingAudioOrchestrator",
  "captureService",
  "gpuRendererService",
  "transcodeService",
  "captureSaveService",
  "captureOrchestrator",
  "preferencesOrchestrator",
  "fullscreenService",
  "cinematicModeService",
  "displayModeOrchestrator",
  "updateService",
  "updateUiService",
  "updateOrchestrator",
  "notesService",
  "uiSetupOrchestrator",
  "animationPerformanceService",
  "bodyClassManager",
  "animationPerformanceOrchestrator",
  "metricsAdapter",
  "performanceMetricsService",
  "performanceMetricsOrchestrator",
  "visibilityAdapter",
  "userActivityAdapter",
  "reducedMotionAdapter",
  "performanceStateService",
  "performanceStateOrchestrator",
  "appOrchestrator",
  "browserMediaService",
  "presentationModeService",
  "canvasLifecycleService",
  "gpuRenderLoopService",
  "gpuWorkerManager",
  "streamHealthService",
  "viewportService",
  "captureUiBridge",
  "transcodeUiBridge",
  "uiEventBridge",
  "uiEffects"
];
    for (const token of staticTokens) {
      this.registrations[token] = {};
    }

    // Pre-seed overrides
    for (const [key, val] of Object.entries(overrides)) {
      const unwrapped = val && typeof val === 'object' && 'value' in val ? val.value : val;
      this.instances.set(key, unwrapped);
      this.cache.set(key, { value: unwrapped });
      this.registrations[key] = val;
    }
  }

  public get cradle(): any {
    return new Proxy({}, {
      get: (_target: object, prop: string | symbol) => {
        if (typeof prop === 'string' && prop in this.registrations) {
          return this.resolve(prop);
        }
        return undefined;
      },
      has: (_target: object, prop: string | symbol) => {
        return typeof prop === 'string' && prop in this.registrations;
      },
      ownKeys: () => []
    }) as any;
  }

  public register(registrations: Record<string, any>) {
    for (const [key, resolver] of Object.entries(registrations)) {
      this.registrations[key] = resolver;
      const unwrapped = resolver && typeof resolver === 'object' && 'value' in resolver ? resolver.value : resolver;
      this.instances.set(key, unwrapped);
      this.cache.set(key, { value: unwrapped });
    }
  }

  public resolve<T = unknown>(token: string): T {
    if (this.instances.has(token)) {
      return this.instances.get(token) as T;
    }

    let instance: any;
    switch (token) {
      // Standard Infrastructure & Factories
      case 'storageService':
        instance = new BrowserStorageAdapter({ protectedKeys: PROTECTED_STORAGE_KEYS });
        break;
      case 'deviceIpcAdapter':
        instance = new DeviceIpcAdapter({
          eventBus: this.resolve('eventBus'),
          logger: this.resolve('loggerFactory').create('DeviceIpcAdapter')
        });
        break;
      case 'deviceChangeDebounceAdapter':
        instance = new DeviceChangeDebounceAdapter({
          browserMediaService: this.resolve('browserMediaService'),
          logger: this.resolve('loggerFactory').create('DeviceChangeDebounceAdapter')
        });
        break;
      case 'canvasRenderLoopService':
        instance = new StreamingCanvasRenderLoopService(
          this.resolve('loggerFactory').create('StreamingCanvasRenderLoopService'),
          this.resolve('animationCache')
        );
        break;
      case 'gpuFrameBuffer':
        instance = new GpuFrameBuffer({ loggerFactory: this.resolve('loggerFactory') });
        break;
      case 'streamingRendererFactory': {
        const rendererProviders = {
          gpu: (deps: any) => new StreamingGpuRendererAdapter(deps),
          canvas2d: (deps: any) => new StreamingCanvas2DRendererAdapter(deps)
        };
        const rendererFactory = new StreamingRendererFactory(
          this.resolve('eventBus'),
          this.resolve('loggerFactory'),
          rendererProviders
        );
        rendererFactory.initialize();
        instance = rendererFactory;
        break;
      }
      case 'ipcClient': {
        const globalWindow = window as any;
        if (!globalWindow.deviceAPI) {
          throw new Error('deviceAPI is not available in the renderer. The preload script may have failed to load.');
        }
        instance = globalWindow.deviceAPI;
        break;
      }
      case 'deviceStatusProvider':
        instance = new DeviceIpcStatusAdapter(this.resolve('ipcClient'));
        break;
      case 'adapterFactory': {
        const adapterClasses = new Map([[chromaticConfig.id, DeviceChromaticAdapter]]);
        const adapterFactory = new StreamingAdapterFactory(
          this.resolve('eventBus'),
          this.resolve('loggerFactory'),
          this.resolve('browserMediaService'),
          adapterClasses
        );
        adapterFactory.initialize();
        instance = adapterFactory;
        break;
      }
      case 'uiComponentRegistry':
        instance = new UIComponentRegistry({
          componentDefinitions: rendererUiComponentDefinitions,
          loggerFactory: this.resolve('loggerFactory')
        });
        break;
      case 'animationCache':
        instance = new AnimationCache();
        break;

      // Scanned @Service class instantiations
      case 'eventBus':
        instance = new EventBus(this.cradle);
        break;
      case 'loggerFactory':
        instance = new RendererLogger();
        break;
      case 'deviceConnectionService':
        instance = new DeviceConnectionService(this.cradle);
        break;
      case 'deviceStorageService':
        instance = new DeviceStorageService(this.cradle);
        break;
      case 'deviceMediaService':
        instance = new DeviceMediaService(this.cradle);
        break;
      case 'deviceService':
        instance = new DeviceService(this.cradle);
        break;
      case 'deviceOperationSequencer':
        instance = new DeviceOperationSequencerService(this.cradle);
        break;
      case 'deviceOrchestrator':
        instance = new DeviceOrchestrator(this.cradle);
        break;
      case 'streamingService':
        instance = new StreamingService(this.cradle);
        break;
      case 'appState':
        instance = new AppState(this.cradle);
        break;
      case 'streamViewService':
        instance = new StreamingViewService(this.cradle);
        break;
      case 'renderPipelineService':
        instance = new StreamingRenderPipelineService(this.cradle);
        break;
      case 'gpuRecordingService':
        instance = new CaptureGpuRecordingService(this.cradle);
        break;
      case 'settingsService':
        instance = new SettingsService(this.cradle);
        break;
      case 'streamingOrchestrator':
        instance = new StreamingOrchestrator(this.cradle);
        break;
      case 'streamingAudioPipelineService':
        instance = new StreamingAudioPipelineService(this.cradle);
        break;
      case 'streamingAudioOrchestrator':
        instance = new StreamingAudioOrchestrator(this.cradle);
        break;
      case 'captureService':
        instance = new CaptureService(this.cradle);
        break;
      case 'gpuRendererService':
        instance = new StreamingGpuRendererService(this.cradle);
        break;
      case 'transcodeService':
        instance = new TranscodeService(this.cradle);
        break;
      case 'captureSaveService':
        instance = new CaptureSaveService(this.cradle);
        break;
      case 'captureOrchestrator':
        instance = new CaptureOrchestrator(this.cradle);
        break;
      case 'preferencesOrchestrator':
        instance = new SettingsPreferencesOrchestrator(this.cradle);
        break;
      case 'fullscreenService':
        instance = new SettingsFullscreenService(this.cradle);
        break;
      case 'cinematicModeService':
        instance = new SettingsCinematicModeService(this.cradle);
        break;
      case 'displayModeOrchestrator':
        instance = new SettingsDisplayModeOrchestrator(this.cradle);
        break;
      case 'updateService':
        instance = new UpdateService(this.cradle);
        break;
      case 'updateUiService':
        instance = new UpdateUiService(this.cradle);
        break;
      case 'updateOrchestrator':
        instance = new UpdateOrchestrator(this.cradle);
        break;
      case 'notesService':
        instance = new NotesService(this.cradle);
        break;
      case 'uiSetupOrchestrator':
        instance = new UISetupOrchestrator(this.cradle);
        break;
      case 'animationPerformanceService':
        instance = new PerformanceAnimationService(this.cradle);
        break;
      case 'bodyClassManager':
        instance = new BodyClassManager();
        break;
      case 'animationPerformanceOrchestrator':
        instance = new PerformanceAnimationOrchestrator(this.cradle);
        break;
      case 'metricsAdapter':
        instance = new MetricsAdapter();
        break;
      case 'performanceMetricsService':
        instance = new PerformanceMetricsService(this.cradle);
        break;
      case 'performanceMetricsOrchestrator':
        instance = new PerformanceMetricsOrchestrator(this.cradle);
        break;
      case 'visibilityAdapter':
        instance = new VisibilityAdapter();
        break;
      case 'userActivityAdapter':
        instance = new UserActivityAdapter();
        break;
      case 'reducedMotionAdapter':
        instance = new ReducedMotionAdapter();
        break;
      case 'performanceStateService':
        instance = new PerformanceStateService(this.cradle);
        break;
      case 'performanceStateOrchestrator':
        instance = new PerformanceStateOrchestrator(this.cradle);
        break;
      case 'appOrchestrator':
        instance = new AppOrchestrator(this.cradle);
        break;
      case 'browserMediaService':
        instance = new BrowserMediaAdapter();
        break;
      case 'presentationModeService':
        instance = new PresentationModeService(this.cradle);
        break;
      case 'canvasLifecycleService':
        instance = new StreamingCanvasLifecycleService(this.cradle);
        break;
      case 'gpuRenderLoopService':
        instance = new StreamingGpuRenderLoopService(this.cradle);
        break;
      case 'gpuWorkerManager':
        instance = new GpuWorkerManager(this.cradle);
        break;
      case 'streamHealthService':
        instance = new StreamingHealthService(this.cradle);
        break;
      case 'viewportService':
        instance = new StreamingViewportService(this.cradle);
        break;
      case 'captureUiBridge':
        instance = new CaptureUIBridge(this.cradle);
        break;
      case 'transcodeUiBridge':
        instance = new TranscodeUIBridge(this.cradle);
        break;
      case 'uiEventBridge':
        instance = new UIEventBridge(this.cradle);
        break;
      case 'uiEffects':
        instance = new UIEffects(this.cradle);
        break;

      default:
        throw new Error("[GeneratedContainer] Could not resolve token: " + token);
    }

    this.instances.set(token, instance);
    this.cache.set(token, { value: instance });
    this.registrations[token] = { value: instance };
    return instance as T;
  }

  public async dispose(): Promise<void> {
    for (const [token, instance] of this.instances.entries()) {
      if (!instance) continue;
      if (typeof instance.dispose === 'function') {
        try {
          await instance.dispose();
        } catch (err) {
          console.error("Error disposing " + token + ":", err);
        }
      } else if (typeof instance.cleanup === 'function') {
        try {
          await instance.cleanup();
        } catch (err) {
          console.error("Error cleaning up " + token + ":", err);
        }
      }
    }
    this.instances.clear();
    this.cache.clear();
    this.registrations = {};
  }
}
